/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import java.time.LocalDate;
import javax.swing.JOptionPane;
import manejo.*;
import manejo.*;
import modelo.Prestamos;

/**
 *
 * @author Ing. Hector Acevedo
 */
public class PrestamosDevoluciones extends javax.swing.JPanel {

    ListaLibros listaLibros = ListaLibros.getListaLibros();
    ListaPersona listaPersonas = ListaPersona.getListaPersona();
    ListaPrestamos listaPrestamos = ListaPrestamos.getPrestamos();
    
    /**
     * Creates new form PrestamosDevoluciones
     */
    public PrestamosDevoluciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_idUsuario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_codigoLibro = new javax.swing.JTextField();
        btn_prestar = new javax.swing.JButton();
        btn_devolver = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_codigoPrestamos = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PRESTAMOS Y DEVOLUCIONES DE LIBROS");

        jLabel2.setText("En este apartado se lleva a cabo el proceso para prestar o devolver libros.");

        jLabel3.setText("Identificacion del Usuario:");

        jLabel4.setText("Codigo del Libro:");

        btn_prestar.setText("PRESTAR LIBRO");
        btn_prestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prestarActionPerformed(evt);
            }
        });

        btn_devolver.setText("DEVOLVER LIBRO");
        btn_devolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_devolverActionPerformed(evt);
            }
        });

        jLabel5.setText("Codigo Prestamo:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_idUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_codigoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_codigoPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(364, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_prestar, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94)
                .addComponent(btn_devolver, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_idUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_codigoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_codigoPrestamos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_prestar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_devolver, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarCampos(){
        txt_codigoLibro.setText("");
        txt_codigoPrestamos.setText("");
        txt_idUsuario.setText("");
    }
    private void btn_prestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prestarActionPerformed
        try{
            int codigoPrestamo = Integer.parseInt(txt_codigoPrestamos.getText());
            int idUsuario = Integer.parseInt(txt_idUsuario.getText());
            int codigoLibro = Integer.parseInt(txt_codigoLibro.getText());
            
            //Instancia de los Nodos
            NodoPersonas nodoPersonas = listaPersonas.buscar(idUsuario);
            NodoLibros nodoLibros = listaLibros.buscarPorCodigo(codigoLibro);
            NodoPrestamos nodoPrestamos;
            //Instancia de la clase Prestamos
            Prestamos prestamos;
            
            LocalDate fecha = LocalDate.now();
            
            if(listaPrestamos.verificarExistencia(codigoLibro, idUsuario) == false){
                if((nodoPersonas != null && nodoLibros != null)){

                    int cantLibros = nodoLibros.getLibros().getCantidad();

                    if(cantLibros > 0){
                        nodoPrestamos = new NodoPrestamos();
                        int nuevaCantidad;

                        prestamos = new Prestamos();
                        prestamos.setIdPersona(idUsuario);
                        prestamos.setIdLibro(codigoLibro);
                        prestamos.setCodigo(codigoPrestamo);
                        prestamos.setFechaPrestamos(fecha);
                        prestamos.setActivo(true);

                        nodoPrestamos.setPrestamos(prestamos);
                        listaPrestamos.agragarPrestamo(nodoPrestamos);

                        nuevaCantidad = cantLibros -1;
                        nodoLibros.getLibros().setCantidad(nuevaCantidad);

                        JOptionPane.showMessageDialog(null, "Se ha realizado el prestamo del libro " + nodoLibros.getLibros().getTitulo() + " al usuario " + nodoPersonas.getPersona().getNombre(), null, JOptionPane.INFORMATION_MESSAGE);
                        
                        limpiarCampos();
                    }else{
                        JOptionPane.showMessageDialog(null, "Este libro no esta disponible para prestar, Espere que otro usuario lo devuelva", null, JOptionPane.ERROR_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "No se encontro el usuario con esta identificacion o el libro con ese codigo", null, JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Este usuario ya ha prestado este libro", null, JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            e.printStackTrace();
            System.out.println("Ha ocurrido un error al tratar de prestar el libro");
        }
    }//GEN-LAST:event_btn_prestarActionPerformed

    private void btn_devolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_devolverActionPerformed
        try {
            int codigoLibro = Integer.parseInt(txt_codigoLibro.getText());
            int idUsuario = Integer.parseInt(txt_idUsuario.getText());
            
            NodoPersonas nodoPersonas = listaPersonas.buscar(idUsuario);
            NodoLibros nodoLibros = listaLibros.buscarPorCodigo(codigoLibro);
            NodoPrestamos nodoPrestamos =listaPrestamos.buscarPrestamo(codigoLibro, idUsuario);

            if(nodoPrestamos != null && nodoPrestamos.getPrestamos().getActivo() == true){
                nodoPrestamos.getPrestamos().setActivo(false);

                int cantidad = nodoLibros.getLibros().getCantidad();
                nodoLibros.getLibros().setCantidad(cantidad + 1);

                JOptionPane.showMessageDialog(null, "Se ha devuelto el libro " + nodoLibros.getLibros().getTitulo() + "\nque se encontraba en posesion del usuario " + nodoPersonas.getPersona().getNombre(), null, JOptionPane.INFORMATION_MESSAGE);
                
                limpiarCampos();
            }else{
                JOptionPane.showMessageDialog(null, "No se encontro el prestamo de este libro", null, JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Ha ocurrido un error al hacer la funcion de devolver el libro");
        }
    }//GEN-LAST:event_btn_devolverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_devolver;
    private javax.swing.JButton btn_prestar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txt_codigoLibro;
    private javax.swing.JTextField txt_codigoPrestamos;
    private javax.swing.JTextField txt_idUsuario;
    // End of variables declaration//GEN-END:variables
}
